# Generated by Django 4.1 on 2022-09-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_on',
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
